#!/usr/bin/env python

import sys
import os
import re
import subprocess

message_file = sys.argv[1]
message = open(message_file,'r').read().strip()

commit_message_convention_help = "[ID-{NUMBER}]: {Descriptive comment}"

message_checker = re.compile(r"\[[A-Z]*-{1}[0-9]*\]:.*")

if message_checker.match(message):
	print "Nice job, " + subprocess.check_output(["git","config","--get","user.name"]).strip()
	exit(0)
else:
	print "[POLICY]: Wrong commit message"
	print '[ERROR]:  "{}" does not match the defined naming convention'.format(message)
	print '[CONVENTION]: {}'.format(commit_message_convention_help)
	exit(1)