#!/usr/bin/env python

import sys
import os
import re
import subprocess

message_file = sys.argv[1]
message = open(message_file,'r')

message_checker = re.compile(r"\[[A-Z]*-{1}[0-9]*\]:.*")

if message_checker.match(message.read()):
	print "Nice job, " + subprocess.check_output(["git","config","--get","user.name"]).strip()
	exit(0)
else:
	print "[POLICY]: Wrong commit message"
	exit(1)