#!/usr/bin/env python
import subprocess 
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

print "Updating server info for dumb transports"
subprocess.call(["git","update-server-info"])